import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Sana Next App',
  description: 'Generated by create next app',
};

type Time = {
  datetime: string;
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const res = await fetch(
    'http://worldtimeapi.org/api/timezone/America/Chicago',
    {
      next: {
        revalidate: 3,
      },
    }
  );
  const data: Time = await res.json();

  return (
    <html lang="en">
      <body>
        <h1>{data.datetime}</h1>
        {children}
      </body>
    </html>
  );
}
